CREATE TABLE IF NOT EXISTS TASRPEDIDOCABECALHO (
    IDPEDIDO TEXT PRIMARY KEY,
    CODPARC INTEGER,
    DTNEG INTEGER,
    DTENTREGA INTEGER,
    CODTIPVENDA INTEGER,
    CODUSU INTEGER,
    SINCRONIZADO TEXT,
    FINALIZADO TEXT,
    OBSERVACAO TEXT,
    EXCLUIDO TEXT
);