CREATE TABLE IF NOT EXISTS TASRPEDIDOITENS (
    IDPEDIDO TEXT,
    CODPROD INTEGER,
    CONTROLE TEXT,
    QTDNEG INTEGER,
    VLRUNITARIO REAL,
    FOREIGN KEY (IDPEDIDO) REFERENCES TASRPEDIDOCABECALHO(IDPEDIDO)
);